import { DevIsland } from '@/components/dev-island/dev-island';
import { Toaster } from '@/components/ui/sonner';
import type { Metadata } from 'next';
import { Poppins } from 'next/font/google';
import OfflineAlert from '../components//offlineMessage/OfflineAlert';
import '../globals.css';

const poppinsRegular = Poppins({
  subsets: ['latin'],
  weight: '400',
  variable: '--font-poppins-regular',
  display: 'swap',
});

const poppinsMedium = Poppins({
  subsets: ['latin'],
  weight: '500',
  variable: '--font-poppins-medium',
  display: 'swap',
});

const poppinsSemiBold = Poppins({
  subsets: ['latin'],
  weight: '600',
  variable: '--font-poppins-semibold',
  display: 'swap',
});

export const metadata: Metadata = {
  title: 'Fintech | Ahorro & inversiones',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body
        className={`${poppinsRegular.variable} ${poppinsMedium.variable} ${poppinsSemiBold.variable} antialiased`}
      >
        {children}
        <Toaster />
        <OfflineAlert />
        <DevIsland />
      </body>
    </html>
  );
}
